#--------------------------
# dojo profile config
# https://book.dojoengine.org/framework/config
# https://github.com/dojoengine/dojo/blob/main/examples/simple/dojo_dev.toml
#

[world]
name = "Feral Forge"
description = "In the depths of Death Mountain lies the Feral Forge, a vicious playground where newborn beasts get prepared to rise for battle!."
icon_uri = "https://feral.beta.underware.gg/assets/feral-icon.jpg"
cover_uri = "https://feral.beta.underware.gg/assets/feral-cover.jpg"
website = "https://feral.beta.underware.gg"
seed = "pistols_v1_0_0"

[world.socials]
x = "https://x.com/underware_gg"
github = "https://github.com/rsodre/feral-forge"
# discord = "https://discord.gg/FB2wR6uF"
# telegram = "https://t.me/dojoengine"

[env]
chain_id = "WP_PISTOLS_SLOT"
rpc_url = "https://api.cartridge.gg/x/feral-slot/katana"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x490fbd1ee25354a172b8c8318bbe823addfe641c62839513f4897aa2c7e24f5"
world_block = 1

#--------------------------
# namespaces
#
[namespace]
default = "feral"

#--------------------------
# namespaces
#
[owners]
"feral" = [
  "feral-game_token",
]

#--------------------------
# writers
#
[writers]
"feral" = [
  "feral-game_token",
]

#--------------------------
# init_calldata
#
[init_call_args]
"feral-game_token" = [
]


#--------------------------
# migration
#
[migration]
order_inits = []
skip_contracts = []
