[package] 
name = "feral"
version.workspace = true
edition.workspace = true
cairo-version = ">=2.12.2"
license = "CC0-1.0"

[cairo]
sierra-replace-ids = true
panic-backtrace = true

[dependencies]
starknet = ">=2.12.2"
dojo = "=1.7.2"
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v1.0.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v1.0.0" }
nft_combo = { git = "https://github.com/underware-gg/cairo-nft-combo", branch = "scarb_2.12.2" }
# achievement = { git = "https://github.com/cartridge-gg/arcade", rev = "a4de9f4c38814a19716b6c5f9cbd4213645e9cb1" }
# graffiti = { git = "https://github.com/rsodre/graffiti", rev = "url" }

[dev-dependencies]
cairo_test = ">=2.12.2"
dojo_cairo_test = "=1.7.2"

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[[target.starknet-contract]]
sierra = true
build-external-contracts = [
  "dojo::world::world_contract::world",
#   "achievement::events::index::e_TrophyCreation",
#   "achievement::events::index::e_TrophyProgression",
]

# debug contract size issues
# needed by `sozo build --stats.by-tag`
# https://docs.starknet.io/resources/chain-info/
# max felts = 81,920 felts
# casm = true
