#
# torii config for profile [sepolia]
#
world_address = "0x02098ea5abf3d4e6cd95df962c58ab746d9a7fd67a47cada710ea2e491354cd2"
rpc = "https://api.cartridge.gg/x/feral-slot/katana"

[events]
raw = true

[sql]
historical = [
  # "feral-TrophyProgression",
]

# [grpc]
# subscription_buffer_size = 10000

[indexing]
world_block = 23920
# blocks_chunk_size = 10240 # default: 10240
# max_concurrent_tasks = 40
transactions = true
controllers = true
pending = true
contracts = [
  "erc721:0x063dfbb323632b55ab714d4315775cc2e56f6bfdce49230aad9b2490763c0958", # game_token
]
